# Generated by Django 4.2 on 2026-06-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo', models.CharField(max_length=20, unique=True)),
                ('periodo', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=20)),
                ('comentario_observacion', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta', to='proyectos.grupo')),
            ],
            options={
                'db_table': 'propuesta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Admin')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('HISTORICO', 'Historico'), ('NUEVO', 'Nuevo')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ciclo', models.CharField(max_length=10)),
                ('codigo_seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, choices=[('EN_DESARROLLO', 'En Desarrollo'), ('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No Aprobado')], max_length=20, null=True)),
                ('comentario_evaluacion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyectos.grupo')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='PropuestaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('version_fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='proyectos.propuesta')),
            ],
            options={
                'db_table': 'propuesta_version',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='proyectos.usuario')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='proyectos.usuario')),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='GrupoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='proyectos.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='proyectos.grupo')),
            ],
            options={
                'db_table': 'grupo_integrante',
                'unique_together': {('grupo', 'estudiante')},
            },
        ),
    ]
